version: '3.5'
networks:
  phpldapadminNet:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/24

services:
  phpldapadmin:
    #image: johann8/alpine-glpi:${VERSION}
    image: johann8/phpldapadmin:${PLA_VERSION}
    container_name: phpldapadmin
    restart: unless-stopped
    #volumes:
      #- ${DOCKERDIR}/data/html:/var/www/html
    ports:
      - 8083:8080
    environment:
      - TZ=${TZ}
      - PHPLDAPADMIN_LANGUAGE=${PHPLDAPADMIN_LANGUAGE}
      - PHPLDAPADMIN_PASSWORD_HASH=${PHPLDAPADMIN_PASSWORD_HASH}
      - PHPLDAPADMIN_SERVER_NAME=${PHPLDAPADMIN_SERVER_NAME}
      - PHPLDAPADMIN_SERVER_HOST=${PHPLDAPADMIN_SERVER_HOST}
      - PHPLDAPADMIN_BIND_ID=${PHPLDAPADMIN_BIND_ID}
    networks:
      - phpldapadminNet

